// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhfQeeiJFkwrB6oCKxZOO6EaI-xuisQ8Q',
    appId: '1:815072394959:web:0672807fb4d99ffb3781ba',
    messagingSenderId: '815072394959',
    projectId: 'nichetechtravelapp',
    authDomain: 'nichetechtravelapp.firebaseapp.com',
    storageBucket: 'nichetechtravelapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO6RxvF1U9Cv1WAlbdNHKitbGSUAXmVfY',
    appId: '1:815072394959:android:699ea968b4a40aab3781ba',
    messagingSenderId: '815072394959',
    projectId: 'nichetechtravelapp',
    storageBucket: 'nichetechtravelapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJzG6dVlSkladMryTTJhO2ZdhbidmiR4Y',
    appId: '1:815072394959:ios:7d2d57496c1f0ff43781ba',
    messagingSenderId: '815072394959',
    projectId: 'nichetechtravelapp',
    storageBucket: 'nichetechtravelapp.appspot.com',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJzG6dVlSkladMryTTJhO2ZdhbidmiR4Y',
    appId: '1:815072394959:ios:5c1b9514e2df89e93781ba',
    messagingSenderId: '815072394959',
    projectId: 'nichetechtravelapp',
    storageBucket: 'nichetechtravelapp.appspot.com',
    iosBundleId: 'com.example.travel.RunnerTests',
  );
}
